//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainUser
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int idInventory { get; set; }
        public int partNumber { get; set; }
        public string partDescription { get; set; }
        public int partQuantity { get; set; }
        public decimal partCost { get; set; }
    }
}
